codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_no_uploads: error
    patch:
      default:
        target: 70%
        threshold: 2%
        if_no_uploads: success

flags:
  backend:
    paths:
      - backend/
  frontend:
    paths:
      - frontend/

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
